public class Dev {
    public static void DevJob(){
        system.debug('–	Core of the team Translate the human language to system language \n Develop software applications and programmes \n Consist of cross technical part (LWC, Integration, UI, UX)\n Type high quality code (best practices)\n Consist of junior and senior dev\n Responsible to create or update documentation/n Responsible for the whitebox/unit testing');
    }
}